<?php /** @var \Amasty\GoogleMap\Block\Map $block */ ?>
<div class="amgooglemap_mapblock">
    <div class="amgooglemap-canvas" id="<?= $block->escapeHtmlAttr($block->getMapId()) ?>"
         style="<?= $block->escapeHtmlAttr($block->getStyles()) ?>">
    </div>
</div>
<script>
    require([
        "https://maps.googleapis.com/maps/api/js?<?= $block->escapeUrl($block->getApiKey()) ?>"
    ], function () {
        var mapLatLng = new google.maps.LatLng(<?= (float)$block->getLatitude() ?>, <?= (float)$block->getLongitude() ?>);
        var mapOptions = {
            draggable: <?= (bool)$block->getIsDraggable() ? 'true' : 'false'; ?>,
            zoom: <?= (int)$block->getZoom() ?>,
            center: mapLatLng,
            mapTypeId: '<?= $block->escapeJs($block->getMapType()) ?>'
        };

        // draw map
        var amMap = new google.maps.Map(document.getElementById("<?= $block->escapeJs($block->getMapId()) ?>"), mapOptions);

        // add Marker to map
        var marker = new google.maps.Marker({
            position: mapLatLng,
            map: amMap,
            animation: google.maps.Animation.DROP,
            title: '<?= $block->escapeJs($block->getMarkerTitle()) ?>'
        });
    });
</script>